"""
Reads fundamentals-content-template.xlsx and generates import.sql
to upsert into Supabase (paste the output into the SQL Editor).

Usage:
    python3 scripts/import_xlsx.py
    # then paste scripts/import.sql into Supabase SQL Editor
"""
import re
import os
from openpyxl import load_workbook

XLSX = os.path.expanduser('~/Downloads/fundamentals-content-template.xlsx')
OUT  = os.path.join(os.path.dirname(__file__), 'import.sql')

# ── Type overrides where spreadsheet value doesn't match planner usage ────────
TYPE_OVERRIDES = {
    'space-invaders':               'throwing',   # sheet says warmup, planner uses in throwing slot
    'rollerball':                   'cooldown',   # sheet says kicking, planner uses in cooldown slot
}

def slugify(raw):
    """cone-rescue → cone-rescue, 'Mario&Bowzers' → mario-bowzers, etc."""
    s = str(raw).strip()
    s = s.replace('&', '')
    s = re.sub(r'[^a-zA-Z0-9\-]', '-', s)
    s = re.sub(r'-+', '-', s).strip('-').lower()
    return s

def pg_array(items):
    """Build a Postgres TEXT[] literal from a list of strings."""
    def esc(s):
        # Single-quoted string literals; escape single quotes as ''
        return "'" + str(s).replace("'", "''") + "'"
    return 'ARRAY[' + ','.join(esc(i) for i in items) + ']::TEXT[]'

def pg_str(s):
    """Single-quoted Postgres string with apostrophes escaped as ''."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"

def pg_null(s):
    return 'NULL' if (s is None or str(s).strip() == '') else pg_str(s)

def val(cell):
    v = cell.value
    if v is None:
        return None
    v = str(v).strip()
    return v if v else None

wb = load_workbook(XLSX, data_only=True)
ab_ws  = wb['Activity Bank']
wp_ws  = wb['Weekly Planner']

lines = []
lines.append('-- ─── Fundamentals App — Spreadsheet Import ─────────────────────────────────')
lines.append('-- Generated by scripts/import_xlsx.py')
lines.append('-- Paste into Supabase Dashboard → SQL Editor → Run')
lines.append('')

# ── Activity Bank (rows 3+, skip rows 1-2 which are header/hint) ─────────────
lines.append('-- ═══ ACTIVITIES ════════════════════════════════════════════════════════════')
lines.append('')

for row in ab_ws.iter_rows(min_row=3):
    # Column mapping (1-based → 0-based index)
    cells = [c for c in row]
    if len(cells) < 2:
        continue
    raw_id = val(cells[0])
    if not raw_id:
        continue

    activity_id   = slugify(raw_id)
    name          = val(cells[1])
    act_type      = val(cells[2]) or 'warmup'
    skill_cue     = val(cells[3])
    equipment_str = val(cells[4])
    image_1       = val(cells[5])
    image_2       = val(cells[6])

    # Instructions — columns H–M (indices 7–12), filter blanks
    raw_instructions = [val(cells[i]) for i in range(7, 13) if i < len(cells)]
    instructions = [s for s in raw_instructions if s]

    coaching_note = val(cells[13]) if len(cells) > 13 else None
    p1_note       = val(cells[14]) if len(cells) > 14 else None

    # Extensions — columns P–T (indices 15–19), filter blanks
    raw_ext = [val(cells[i]) for i in range(15, 20) if i < len(cells)]
    extension = [s for s in raw_ext if s]

    easier = val(cells[20]) if len(cells) > 20 else None
    harder = val(cells[21]) if len(cells) > 21 else None

    # Apply type overrides
    if activity_id in TYPE_OVERRIDES:
        corrected = TYPE_OVERRIDES[activity_id]
        lines.append(f'-- NOTE: type corrected from {pg_str(act_type)} → {pg_str(corrected)} for {activity_id}')
        act_type = corrected

    # Build images array
    images = [f for f in [image_1, image_2] if f]
    # Equipment array
    equipment = [e.strip() for e in equipment_str.split(',')] if equipment_str else []

    lines.append(f'-- {activity_id}')
    lines.append('INSERT INTO public.activities')
    lines.append('  (id, name, type, skill_cue, equipment, images, instructions, coaching_note, p1_note, extension, easier, harder)')
    lines.append('VALUES (')
    lines.append(f'  {pg_str(activity_id)},')
    lines.append(f'  {pg_str(name)},')
    lines.append(f'  {pg_str(act_type)},')
    lines.append(f'  {pg_null(skill_cue)},')
    lines.append(f'  {pg_array(equipment)},')
    lines.append(f'  {pg_array(images)},')
    lines.append(f'  {pg_array(instructions)},')
    lines.append(f'  {pg_null(coaching_note)},')
    lines.append(f'  {pg_null(p1_note)},')
    lines.append(f'  {pg_array(extension)},')
    lines.append(f'  {pg_null(easier)},')
    lines.append(f'  {pg_null(harder)}')
    lines.append(')')
    lines.append('ON CONFLICT (id) DO UPDATE SET')
    lines.append('  name          = EXCLUDED.name,')
    lines.append('  type          = EXCLUDED.type,')
    lines.append('  skill_cue     = EXCLUDED.skill_cue,')
    lines.append('  equipment     = EXCLUDED.equipment,')
    lines.append('  images        = EXCLUDED.images,')
    lines.append('  instructions  = EXCLUDED.instructions,')
    lines.append('  coaching_note = EXCLUDED.coaching_note,')
    lines.append('  p1_note       = EXCLUDED.p1_note,')
    lines.append('  extension     = EXCLUDED.extension,')
    lines.append('  easier        = EXCLUDED.easier,')
    lines.append('  harder        = EXCLUDED.harder,')
    lines.append('  updated_at    = NOW();')
    lines.append('')

# ── Weekly Planner (rows 3+, skip blank weeks) ────────────────────────────────
lines.append('')
lines.append('-- ═══ WEEK PLANS & SESSION SLOTS ════════════════════════════════════════════')
lines.append('')

SECTION_COLS = [
    ('warmup',   2, 3),    # warmup_1=col C (idx2), warmup_2=col D (idx3)
    ('throwing', 4, 5),
    ('kicking',  6, 7),
    ('cooldown', 8, None), # only one cooldown slot
]

for row in wp_ws.iter_rows(min_row=3):
    cells = [c for c in row]
    if len(cells) < 2:
        continue
    week_num_raw = val(cells[0])
    focus        = val(cells[1])
    if not week_num_raw or not focus:
        continue  # skip empty weeks

    week_num = int(float(str(week_num_raw)))

    # Layout notes — columns J–N (indices 9–13)
    layout_notes = [val(cells[i]) for i in range(9, 14) if i < len(cells)]
    layout_notes = [n for n in layout_notes if n]

    lines.append(f'-- Week {week_num}: {focus}')
    lines.append('INSERT INTO public.week_plans (week_number, focus, layout_notes, is_active)')
    lines.append(f'VALUES ({week_num}, {pg_str(focus)}, {pg_array(layout_notes)}, true)')
    lines.append('ON CONFLICT (week_number) DO UPDATE SET')
    lines.append('  focus        = EXCLUDED.focus,')
    lines.append('  layout_notes = EXCLUDED.layout_notes,')
    lines.append('  is_active    = true;')
    lines.append('')
    lines.append(f'DELETE FROM public.session_slots WHERE week_number = {week_num};')
    lines.append('')

    slot_rows = []
    for section, col1, col2 in SECTION_COLS:
        act1 = val(cells[col1]) if col1 < len(cells) else None
        act2 = val(cells[col2]) if (col2 is not None and col2 < len(cells)) else None
        if act1:
            slot_rows.append((week_num, section, 1, slugify(act1)))
        if act2:
            slot_rows.append((week_num, section, 2, slugify(act2)))

    if slot_rows:
        lines.append(f'INSERT INTO public.session_slots (week_number, section, slot_order, activity_id) VALUES')
        for i, (wn, sec, order, aid) in enumerate(slot_rows):
            comma = ',' if i < len(slot_rows) - 1 else ';'
            lines.append(f"  ({wn}, '{sec}', {order}, '{aid}'){comma}")
    lines.append('')

sql = '\n'.join(lines)

with open(OUT, 'w') as f:
    f.write(sql)

print(f'✓ Written {len([l for l in lines if l.startswith("INSERT")])} INSERT statements')
print(f'✓ Output: {OUT}')
